### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by clsn** [bbusschots/hsxkpasswd#25]
In Build.PL and also in lib/Crypt/HSXKPasswd.pm you refer to "Steve Gibson's Passord[sic] Haystacks", instead of "Password".  Is it less disruptive for you if I file this issue or a pull request?

**Comment by bbusschots** [comment]
Fixed in commit: https://github.com/bbusschots/hsxkpasswd/commit/bbe389a1a3ca1a947361924829ac5fb430ac5729

Thanks for logging the issue.
