### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by szepeviktor** [bbusschots/hsxkpasswd#5]
Please consider CPAN as a distribution point.

**Comment by bbusschots-nuim** [comment]
It's something I have considered, and plan to do, but I've never packaged anything for CPAN before, so I'm not really sure where to begin.

If anyone would like to contribute the code changes needed to get the module ready for submission to CPAN I'd be very appreciative :)

**Comment by bbusschots** [comment]
The changes have now been made to prepare the module for CPAN, and a beta of the version I hope to submit to CPAN within the next few weeks has been released: https://github.com/bbusschots/xkpasswd.pm/releases/tag/v3.1.1

Even before it is in CPAN, it can be installed with the usual:

perl Build.PL
./Build
./Build test
./Build install

**Comment by bbusschots** [comment]
The module is now available via CPAN: http://search.cpan.org/perldoc?Crypt%3A%3AHSXKPasswd

**Comment by szepeviktor** [comment]
Thank you!
