### ISSUE TITLE
"keys on reference is experimental"

### ISSUE THREAD

**Issue by szepeviktor** [bbusschots/hsxkpasswd#9]
keys on reference is experimental at /usr/local/share/perl/5.20.2/Crypt/HSXKPasswd.pm line 610.
keys on reference is experimental at /usr/local/share/perl/5.20.2/Crypt/HSXKPasswd.pm line 628.
keys on reference is experimental at /usr/local/share/perl/5.20.2/Crypt/HSXKPasswd.pm line 628.

```
perl -v

This is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-gnu-thread-multi
(with 42 registered patches, see perl -V for more detail)
```

Is it intended?

**Comment by bbusschots** [comment]
Nope - not intended - my version of Perl doesn't give those warnings.

**Comment by bbusschots** [comment]
I think I've resolved the problem in this branch: https://github.com/bbusschots/hsxkpasswd/tree/150811-CPANBugFixes

Would you be able to test that branch on your system to verify that my fix is indeed correct?

**Comment by szepeviktor** [comment]
Thank you, those are fixed.

**Comment by szepeviktor** [comment]
You could set up a CI script. Travis has multiple version of perl:
http://docs.travis-ci.com/user/languages/perl/
